name: Deploy to AWS

on:
  push:
    branches:
      - develop  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Gets the latest code from GitHub

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.ACCESSSECRETKEY }}
          aws-region: eu-west-3  

     
      - name: Deploy to S3
        run: |
          aws s3 sync . s3://georgetesting
        if: ${{ github.event_name == 'push' }}  
