pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/OluGeorge/Oludevops.git'
            }
        }

        stage('Build') {
            steps {
                echo 'Building the application...'
                sh 'python3 -m py_compile app.py'  // or npm install, mvn package, etc.
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                // Example: sh 'pytest tests/'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying application...'
                sh 'docker build -t my-app .'
                sh 'docker run -d -p 5000:5000 my-app'
            }
        }
    }
}
